// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLV99IqfSQY1n7C0khzPXa9jWIJrP0ICY',
    appId: '1:344580400447:web:748496df01f2d62a91df8a',
    messagingSenderId: '344580400447',
    projectId: 'routine-mate',
    authDomain: 'routine-mate.firebaseapp.com',
    storageBucket: 'routine-mate.firebasestorage.app',
    measurementId: 'G-9NDXRQWS24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg4ZUZr5cCzVdt2xS2AYcKCn6jKMTPqtc',
    appId: '1:344580400447:android:6091c26fe5a5303991df8a',
    messagingSenderId: '344580400447',
    projectId: 'routine-mate',
    storageBucket: 'routine-mate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLl0sqqWyO5QGbtVOPdpsoodDKofzVLXo',
    appId: '1:344580400447:ios:624741d9c3d1cfae91df8a',
    messagingSenderId: '344580400447',
    projectId: 'routine-mate',
    storageBucket: 'routine-mate.firebasestorage.app',
    iosBundleId: 'com.example17.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLl0sqqWyO5QGbtVOPdpsoodDKofzVLXo',
    appId: '1:344580400447:ios:fbd4541c5874f45091df8a',
    messagingSenderId: '344580400447',
    projectId: 'routine-mate',
    storageBucket: 'routine-mate.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLV99IqfSQY1n7C0khzPXa9jWIJrP0ICY',
    appId: '1:344580400447:web:06476044821fef0591df8a',
    messagingSenderId: '344580400447',
    projectId: 'routine-mate',
    authDomain: 'routine-mate.firebaseapp.com',
    storageBucket: 'routine-mate.firebasestorage.app',
    measurementId: 'G-VPQ84D02R3',
  );
}
